version: '3.8'

services:
  authservice:
    build:
      context: .
      dockerfile: ./app.auth/Dockerfile
    ports:
      - "8080:8080"  # Map port 8080 in the container to port 8080 on the host
    volumes:
      - ./app.auth/AuthService.db:/app/AuthService.db  # Mount the SQLite DB for persistence
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
